version: '3.1'
services:
  odoo:
    image: odoo:16.0
    env_file: priv.env
    depends_on:
      - pgql
    ports:
      - "80:8069"
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  
  pgql:
    image: postgres:15.8-alpine3.19
    env_file: priv.env
    volumes:
      - db:/var/lib/pgsql/data/pgdata

volumes:
  data:
  db:

    